directories:
  output: release
  buildResources: build
appId: com.electron.template
productName: ElectronTemplate
files:
  - filter:
      - dist/**/*
      - main.js
      - package.json
win:
  target: nsis
publish:
  - provider: github
    owner: Kathurjan
    repo: template-electron
electronVersion: 35.1.2
